# travisci config
env:
  global:
  - NONINTERACTIVE=1
  - SKIP_NETWORK_CHECKS=1
  - PRIMARY_HOSTNAME=box.abc.com

language: shell
os: linux
dist: bionic
  
before_install:
  - echo "Check the status of AppArmor"
  - ! sudo aa-status && mount -tsecurityfs securityfs /sys/kernel/security
  - sudo apt-get update
  
install:
  - sudo ./setup/start.sh -v

script:
  - sudo ./tests/runner.sh
