# travisci config
env:
  global:
  - NONINTERACTIVE=1
  - SKIP_NETWORK_CHECKS=1
  - PRIMARY_HOSTNAME=box.abc.com

language: shell
os: linux
dist: bionic
  
before_install:
  - echo "==== DUMP ENVIRONMENT ===="
  - env | sort
  - echo "UMASK=$(umask)"
  #
  - echo "==== DUMP AppArmor Status ===="
  - (sudo aa-status; true)
  #
  - echo "==== System update ===="
  # Do not run 'upgrade'
  - sudo apt-get update
  #
  - echo "==== Install QA/test prerequisites ===="
  # python3-dnspython is used by the python scripts in 'tests' and is
  # not installed by setup
  - sudo apt-get -y install python3-dnspython
  # avoid the lengthy generation of DH params by copying in a prebuilt file
  - sudo mkdir -p /home/user-data/ssl
  - sudo cp ./tests/assets/ssl/dh2048.pem /home/user-data/ssl
  #
  - echo "==== Add the PRIMARY_HOSTNAME to /etc/hosts ===="
  # The PRIMARY_HOSTNAME should point to the interface address not
  # loopback.  That is because of the way MiaB resolves - the local
  # resolver is bind9, which requires valid NS records, which would
  # point back to the local nsd authoritative name server for the
  # domain. We don't have those in QA, so we need the hosts entry.
  - echo "$(source setup/functions.sh; get_default_privateip 4)   $PRIMARY_HOSTNAME" > /tmp/hosts_add.tmp
  - sudo $SHELL -c 'cat /tmp/hosts_add.tmp >>/etc/hosts'
  - (sudo systemctl status -l nsd; true)
  
install:
  - sudo ./setup/start.sh -v

script:
  - sudo sed -i 's|-d|-d -6 -N 1 -n 1|' /etc/systemd/system/multi-user.target.wants/nsd.service
  - sudo systemctl daemon-reload
  - sudo systemctl restart nsd
  - sudo systemctl status -l nsd
  - sudo cat /var/log/nsd.log
  - sudo cat /etc/nsd/nsd.conf
  - sudo nsd-checkconf -o port /etc/nsd/nsd.conf
  - sudo nsd-checkconf -o ip-address /etc/nsd/nsd.conf
  - sudo cat /etc/systemd/system/multi-user.target.wants/nsd.service
  - sudo tail -100 /var/log/syslog
  - sudo ps -efww | grep nsd
  - sudo ss -lp "sport = 8952"
  - sudo ss -lp "sport = :domain"
  - sudo ./tests/runner.sh -dumpoutput -no-smtp-remote
