# travisci config
env:
  global:
  - PRIMARY_HOSTNAME=box.abc.com

language: shell
os: linux
dist: bionic
  
before_install:
  - echo "==== DUMP ENVIRONMENT ===="
  - env | sort
  - echo "UMASK=$(umask)"
  #
  - echo "==== DUMP AppArmor Status ===="
  - (sudo aa-status; true)
  
install:
  - sudo tests/assets/system-setup/remote-nextcloud-docker.sh

script:
  #
  # launch automated tests, but skip tests that require remote
  # smtp support because Travis-CI blocks outgoing port 25
  - sudo tests/runner.sh -dumpoutput -no-smtp-remote default remote-nextcloud
