# travisci config
env:
  global:
  - NONINTERACTIVE=1
  - SKIP_NETWORK_CHECKS=1
  - PRIMARY_HOSTNAME=box.abc.com

language: shell
os: linux
dist: bionic
  
before_install:
  - sudo aa-status
  - sudo apt-get update
  
install:
  - sudo ./setup/start.sh -v

script:
  - sudo ./tests/runner.sh
